name: todo
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  flutter: 3.19.2
  sdk: 3.3.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # https://pub.dev/packages/dio
  dio: ^5.4.3+1
  # https://pub.dev/packages/get_it
  get_it: ^7.7.0
  # https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.2.3
  # https://pub.dev/packages/flutter_native_splash
  flutter_native_splash: ^2.4.0
  # https://pub.dev/packages/auto_route
  auto_route: ^8.1.3
  # https://pub.dev/packages/flutter_bloc
  flutter_bloc: ^8.1.6
  # https://pub.dev/packages/logger
  logger: ^2.3.0
  # https://pub.dev/packages/intl
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner:
  build_runner:
  flutter_lints: ^3.0.0
  auto_route_generator: ^8.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: SFUIDisplay
      fonts:
        - asset: assets/fonts/SFUIDisplay-Regular.ttf


flutter_intl:
  enabled: true

flutter_gen:
  output: lib/generated/assets

